<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.webserviceX.NET"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.webserviceX.NET"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="Weatherinvoker">
        <plnk:role name="GlobalWeatherSoap" portType="tns:GlobalWeatherSoap"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.webserviceX.NET" location="WeatherWSDL.wsdl"/>
</wsdl:definitions>
